# Generated by Django 5.0.7 on 2024-07-27 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employees', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='diplome',
            new_name='address',
        ),
        migrations.CreateModel(
            name='AcademicCurriculum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diplome', models.CharField(max_length=50)),
                ('school', models.CharField(max_length=150)),
                ('date_of_obtaining', models.DateField()),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diplomes', to='Employees.employee')),
            ],
        ),
    ]
