# Generated by Django 5.0.7 on 2024-07-27 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employees', '0002_rename_diplome_employee_address_academiccurriculum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='address',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
