# Generated by Django 5.0.7 on 2024-08-02 00:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employees', '0003_alter_employee_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academiccurriculum',
            name='employee_id',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='employee_id',
        ),
        migrations.AddField(
            model_name='academiccurriculum',
            name='employee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Employees.employee'),
        ),
        migrations.AddField(
            model_name='experience',
            name='employee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Employees.employee'),
        ),
    ]
